name: PRs and Branches

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - main
      - master
      - development

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        cfengine: ["lucee@5", "lucee@6", "lucee@7", "adobe@2021", "adobe@2023", "adobe@2025", "boxlang-cfml@1"]
        coldbox: ["^6.0.0", "^7.0.0", "^8.0.0"]
        experimental: [ false ]
        include:
          - cfengine: "lucee@be"
            coldbox: "^6.0.0"
            experimental: true
          - cfengine: "lucee@be"
            coldbox: "^7.0.0"
            experimental: true
          - cfengine: "lucee@be"
            coldbox: "^8.0.0"
            experimental: true
          - cfengine: "adobe@be"
            coldbox: "^6.0.0"
            experimental: true
          - cfengine: "adobe@be"
            coldbox: "^7.0.0"
            experimental: true
          - cfengine: "adobe@be"
            coldbox: "^8.0.0"
            experimental: true
          - cfengine: "boxlang@be"
            coldbox: "^8.0.0"
            experimental: true
          - cfengine: "boxlang@1"
            coldbox: "^8.0.0"
            experimental: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.2.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          install: commandbox-boxlang,commandbox-cfconfig

      - name: Install dependencies
        run: |
          box install
          box install coldbox@{{ matrix.coldbox }} --noSave

      - name: Start server
        run: |
          box server start serverConfigFile="server-${{ matrix.cfengine }}.json" --noSaveSettings --debug
          curl http://127.0.0.1:8500

      - name: Run TestBox Tests
        continue-on-error: ${{ matrix.experimental }}
        run: box testbox run

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.2.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Install CFFormat
        run: box install commandbox-cfformat

      - name: Run CFFormat
        run: box run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cfformat changes